import React from 'react';
import { Typography, Button } from 'antd';

const { Title, Paragraph } = Typography;

const ServiceAndPolicy = () => {
  const handleButtonClick = () => {
    // Define what happens when the button is clicked
    console.log('Button clicked!');
  };

  return (
    <div style={{ maxWidth: '800px', margin: 'auto', padding: '20px', marginTop: '50px' }}>
      <Title style={{marginLeft:'150px'}} level={2}>Privacy Policy </Title>
      <p style={{marginLeft:'150px'}}>Effective date: 01/01/2024</p>
      <Paragraph>
        <h3>1. Introduction</h3>
        <Paragraph>Welcome to FuelSignal, Inc DBA Oodles. </Paragraph>
        <Paragraph>Oodles application (hereinafter referred to as “Service”)</Paragraph>

        Our Privacy Policy governs your visit to

       <a href="/ www.oodlesrewards.com"> www.oodlesrewards.com</a>
       and Oodles Shopify application and explains how we collect, safeguard and disclose information that results from your use of our Service.

We use your data to provide and improve Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.

Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”). 
      </Paragraph>

    
      <Paragraph>
        <h3>2. Definitions</h3>
        SERVICE means the <a href='/www.oodlesrewards.com '>www.oodlesrewards.com </a> website and Shopify app operated by FuelSignal, Inc DBA Oodles. 
      </Paragraph>
      PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). 
      <Paragraph>
    
      </Paragraph>
      USAGE DATA is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). 
      <Paragraph>
      COOKIES are small files stored on your device (computer or mobile device). 
      </Paragraph>

      
      <Paragraph>
      DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data. 
      </Paragraph>
      
      
      <Paragraph>
      DATA PROCESSORS(OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
      </Paragraph>
      
      
      <Paragraph>
      DATA SUBJECT is any living individual who is the subject of Personal Data. 
      </Paragraph>
      
      
      <Paragraph>
      THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
   
      </Paragraph>
      <Paragraph>
        <h3>3. Information Collection and Use</h3>
        We collect several different types of information for various purposes to provide and improve our Service to you. 

      </Paragraph>
      <Paragraph>
        <h3>4. Types of Data Collected</h3>
         <Paragraph>Personal Data </Paragraph>
         While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to: 
         <Paragraph>(a) Email address </Paragraph>
         <Paragraph>(b) First name and last name</Paragraph>
         <Paragraph>(c) Phone number </Paragraph>
         <Paragraph>(d) Address, State, Province, ZIP/Postal code, City</Paragraph>
         <Paragraph>(e) Cookies and Usage Data </Paragraph>
         We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at info@oodlesrewards.com. 
         <Paragraph>USAGE DATA </Paragraph>
         We may also collect information on how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data
<Paragraph>Tracking Cookies Data </Paragraph>
We may use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service. 
<Paragraph>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. </Paragraph>
<h3>Examples of Cookies we use: </h3>


 <Paragraph> (a) Session Cookies: We use Session Cookies to operate our Service.</Paragraph>

 <Paragraph>(b) Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</Paragraph>

 <Paragraph>(c) Security Cookies: We use Security Cookies for security purposes.</Paragraph>

 <Paragraph>(d) Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</Paragraph>


      </Paragraph>
      <Paragraph>
        <h3>5. Use of Data</h3>
        <Paragraph>Oodles uses the collected data for various purposes: </Paragraph>
        <Paragraph>(a) to provide and maintain our Service; </Paragraph>
        <Paragraph>(b) to notify you about changes to our Service; </Paragraph>
        <Paragraph>(c) to allow you to participate in interactive features of our Service when you choose to do so; </Paragraph>
        <Paragraph>(d) To provide customer care and support </Paragraph>
        <Paragraph>(e) To provide analysis or valuable information so that we can improve the Service</Paragraph>
        <Paragraph>(f) to monitor the usage of our Service; </Paragraph>
        <Paragraph>(g) to detect, prevent and address technical issues; </Paragraph>
        <Paragraph>(h)To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information Legal Basis for Processing Personal Data Under GDPR: </Paragraph>
        <Paragraph>If you are from the European Economic Area (EEA), Oodles' legal basis for collecting and using the personal data described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it. </Paragraph>
        <Paragraph>(j)Oodles may process your Personal Data because: </Paragraph>
        <Paragraph>(k) We need to perform a contract with you </Paragraph>
        <Paragraph>(l)You have given us permission to do so </Paragraph>
        <Paragraph>(m)The processing is in our legitimate interests and it is not overridden by your rights</Paragraph>
        <Paragraph>(n)For compliance with a legal obligation </Paragraph>
        <Paragraph>(o)To protect your vital interests or those of others</Paragraph>
        <Paragraph>
          <h3>6. Retention of Data</h3>
          Oodles will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. 
          <Paragraph>Oodles will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods. </Paragraph>
        </Paragraph>
       
      </Paragraph>
      <Paragraph>
        <h3>7. Transfer of Data</h3>
        Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. 
      </Paragraph>
      <Paragraph>If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there. </Paragraph>
      <Paragraph>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. </Paragraph>
      <Paragraph>Oodles will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information. </Paragraph>
      <Paragraph>
        <h3>8. Disclosure of Data</h3>
        <Paragraph>Business Transaction: </Paragraph>
        <Paragraph>If Oodles is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy. </Paragraph>
        <Paragraph>Legal Requirements: </Paragraph>
      </Paragraph>
      <Paragraph>Oodles may disclose your Personal Data in the good faith belief that such action is necessary to </Paragraph>
      <Paragraph>(a) To comply with a legal obligation </Paragraph>
      <Paragraph>(b) To protect and defend the rights or property of Oodles </Paragraph>
      <Paragraph>(b) To protect and defend the rights or property of Oodles </Paragraph>
      <Paragraph>(c) To prevent or investigate possible wrongdoing in connection with the Service </Paragraph>
      <Paragraph>(d)To protect the personal safety of users of the Service or the public </Paragraph>
      <Paragraph>(e) To protect against legal liability </Paragraph>
      <Paragraph>
        <h3>9. Security of Data</h3>
        The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security. 

      </Paragraph>
      <Paragraph><h3>10. Service Providers: </h3>
      We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), to provide the Service on our behalf, to perform Service-related services, or to assist us in analyzing how our Service is used.

These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. 

      </Paragraph>
      <Paragraph>
        <h3>11. Links to Other Sites: </h3>
        Our Service may contain links to other sites that are not operated by us. If you click on a third-party link, you will be directed to that third-party’s site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services. 
      </Paragraph>
      <Paragraph>
        <h3>
        12. Children’s Privacy: 
        </h3>
        Our Service does not address anyone under the age of 13 (“Children”). We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Children have provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers. 

      </Paragraph>
      <Paragraph>
        <h3>13. Changes to This Privacy Policy: </h3>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We encourage you to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. 
<Paragraph>Contact Us: </Paragraph>
If you have any questions about this Privacy Policy, please contact us by email at info@oodlesrewards.com or by mail at:

FuelSignal, Inc DBA Oodles Rewards

1801 Main Street Ste 1300

Houston, Texas 77002

United States

CCPA Privacy Policy (California Residents Only) 

      </Paragraph>
      <Paragraph>This section applies solely to all visitors, users, and others who reside in the State of California (“consumers” or “you”). We adopt this notice to comply with the California Consumer Privacy Act of 2018 (CCPA) and any terms defined in the CCPA have the same meaning when used in this Privacy Policy.
        <Paragraph>
        Controller: 
          </Paragraph> 
          
          </Paragraph>
          <Paragraph>FuelSignal, Inc DBA Oodles with registered office at 1801 Main Street Ste 1300, Houston Texas, 77002, United States is the controller of your personal data. </Paragraph>
          <Paragraph>Purposes: </Paragraph>
          <Paragraph>We process personal data for the following purposes: </Paragraph>
          <Paragraph>(a)To provide and maintain our Service, including to monitor the usage of our Service.</Paragraph>
          <Paragraph>(b)To manage your account and provide you with customer support. </Paragraph>
          <Paragraph>(c)To communicate with you and to respond to your inquiries, including to send you newsletters and marketing communications.</Paragraph>
          <Paragraph>(d)To conduct research and statistical analysis in order to improve our Service.</Paragraph>
          <Paragraph>(e)To comply with legal obligations.</Paragraph>
          <Paragraph>Legal Basis for Processing: 

          </Paragraph>
          <Paragraph>The legal basis for collecting and using the personal data described in this Privacy Policy depends on the personal data we collect and the specific context in which we collect it. We may process your personal data because: </Paragraph>
          <Paragraph>(a)We need to perform a contract with you, such as when you use our app to create a loyalty program or chatbot for your store.</Paragraph>

            <Paragraph>(b)You have given us permission to do so, such as when you opt-in to receive newsletters or marketing communications. </Paragraph>
            <Paragraph>(c)The processing is in our legitimate interests and it is not overridden by your rights, such as for research and statistical analysis, or to improve our app and services. </Paragraph>
            <Paragraph>(d)To comply with the law, such as to comply with a subpoena or similar legal process. </Paragraph>
            <Paragraph>Retention: 
              <Paragraph>We will retain your personal data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies. </Paragraph>
              <Paragraph>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods. </Paragraph>
            </Paragraph>
            <Paragraph>Transfer of Data: 
              <Paragraph>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction. </Paragraph>
              <Paragraph>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. </Paragraph>
              <Paragraph>We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information. </Paragraph>

            </Paragraph>
            <Paragraph>Disclosure of Data: </Paragraph>
            <Paragraph>We may disclose your personal data in the good faith belief that such action is necessary to: 
             
            </Paragraph>
            <Paragraph>(a) To comply with a legal obligation</Paragraph>
            <Paragraph>(b)To protect and defend the rights or property of FuelSignal, Inc DBA Oodles</Paragraph>
            <Paragraph>(c)To prevent or investigate possible wrongdoing in connection with the Service</Paragraph>
            <Paragraph>(d)To protect the personal safety of users of the Service or the public</Paragraph>
            <Paragraph>(e)To protect against legal liability</Paragraph>
            <Paragraph><h4>Security of Data: </h4> </Paragraph>
            <Paragraph>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security. </Paragraph>
            <Paragraph><p>Your Rights: </p></Paragraph>
            <Paragraph>We respect the privacy rights of our Data Subjects and we are committed to processing personal data in accordance with the GDPR. You have the following rights with respect to your personal data: </Paragraph>
            <Paragraph>(a) The right to be informed about the personal data we process on you.</Paragraph>
            <Paragraph>(b) The right of access to the personal data we process on you.</Paragraph>
            <Paragraph>(c) The right to rectification of your personal data.</Paragraph>

            <Paragraph>(d) The right to erasure of your personal data.</Paragraph>
            <Paragraph>(e) The right to restrict processing of your personal data.</Paragraph>
            <Paragraph>(f) The right to object to processing of your personal data.</Paragraph>
            <Paragraph>(g) The right to data portability.</Paragraph>
            <Paragraph>(h) The right to withdraw your consent at any time, where relevant.</Paragraph>
            <Paragraph>(i) The right to complain to a supervisory authority.</Paragraph>
            <Paragraph>If you wish to exercise any of the rights set out above, please contact us at info@oodlesrewards.com. </Paragraph>
            <Paragraph>CCPA Privacy Policy (California Residents Only) </Paragraph>
            <Paragraph>This section applies solely to all visitors, users, and others who reside in the State of California (“consumers” or “you”). We adopt this notice to comply with the California Consumer Privacy Act of 2018 (CCPA) and any terms defined in the CCPA have the same meaning when used in this notice. </Paragraph>
            <Paragraph> Information We Collect: </Paragraph>
            <Paragraph> We may collect the following categories of personal information from you in the past 12 months: </Paragraph>
            <Paragraph> (a)Identifiers such as your name, address, email address, and phone number. </Paragraph>
            <Paragraph> (b)Commercial information, such as records of products or services purchased, obtained, or considered. </Paragraph>
            <Paragraph> (c)Internet or other electronic network activity information, such as browsing history and search history. </Paragraph>
            <Paragraph>(d)Geolocation data. </Paragraph>
            <Paragraph>We collect this information for the following purposes: </Paragraph>
            <Paragraph>(a)To provide and maintain our Service, including to monitor the usage of our Service. </Paragraph>
            <Paragraph>(b)To manage your account and provide you with customer support. </Paragraph>
            <Paragraph>(c)To conduct research and statistical analysis in order to improve our Service. Disclosure of Personal Information</Paragraph>
            <Paragraph>We may disclose your personal information to the following categories of third parties: </Paragraph>
            <Paragraph>(a)Service providers that help us with our business operations. </Paragraph>
            <Paragraph>(b)Law enforcement, government agencies, or authorized third parties, if we are required to do so by law or if we reasonably believe that such action is necessary to protect the safety of our users or the public. </Paragraph>
            <Paragraph>Your Rights: </Paragraph>
            <Paragraph>Under the CCPA, you have the right to: </Paragraph>
            <Paragraph>(a)Request that we disclose to you the personal information we have collected about you in the past 12 months. </Paragraph>
            <Paragraph>(b)Request that we delete any personal information that we have collected from you. </Paragraph>
            <Paragraph>(c)Opt-out of the sale of your personal information. </Paragraph>
            <Paragraph>To exercise your rights, you may contact us at info@oodlesrewards.com. </Paragraph>
            <Paragraph>We will not discriminate against you for exercising any of your CCPA rights. </Paragraph>
            <Paragraph>Changes to This Privacy Policy:</Paragraph>
            <Paragraph>We reserve the right to update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. </Paragraph>
            <Paragraph>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. </Paragraph>
            <Paragraph>Contact Us:</Paragraph>
            <Paragraph> If you have any questions about this Privacy Policy, please contact us at info@oodlesrewards.com.

If you have any other questions or concerns about the Privacy Policy or your personal data then please don't hesitate to reach out to us at info@oodlesrewards.com. We're here to help. </Paragraph>


      
    </div>
  );
};

export default ServiceAndPolicy;
